---
title: "R Notebook"
output: html_notebook
---


## db
```{r}
if("rJava" %in% installed.packages("rJava") == FALSE)install.packages("rJava")
      library(rJava)
if("DBI" %in% installed.packages("DBI") == FALSE)install.packages("DBI")
      library(DBI)
if("RJDBC" %in% installed.packages("RJDBC") == FALSE)install.packages("RJDBC")
      library(RJDBC)
if("XML" %in% installed.packages("XML") == FALSE)install.packages("XML")
      library(XML)
if("memoise" %in% installed.packages("memoise") == FALSE)install.packages("memoise")
      library(memoise)
```

## string
```{r}
if("dplyr" %in% installed.packages("dplyr") == FALSE)install.packages("dplyr")
      library(dplyr)
if("data.table" %in% installed.packages("data.table") == FALSE)install.packages("data.table")
      library(data.table)
if("stringi" %in% installed.packages("stringi") == FALSE)install.packages("stringi")
      library(stringi)
if("stringr" %in% installed.packages("stringr") == FALSE)install.packages("stringr")
      library(stringr)
if("plyr" %in% installed.packages("plyr") == FALSE)install.packages("plyr")
      library(plyr)
```


## tm
```{r}
if("KoNLP" %in% installed.packages("KoNLP") == FALSE)install.packages("KoNLP")
      library(KoNLP)
if("tm" %in% installed.packages("tm") == FALSE)install.packages("tm")
      library(tm)
if("wordcloud" %in% installed.packages("wordcloud") == FALSE)install.packages("wordcloud")
      library(wordcloud)
```


## html
```{r}
if("rvest" %in% installed.packages("rvest") == FALSE)install.packages("rvest")
      library(rvest)
if("shiny" %in% installed.packages("shiny") == FALSE)install.packages("shiny")
      library(shiny)
```

## chart
```{r}
if("ggplot2" %in% installed.packages("ggplot2") == FALSE)install.packages("ggplot2")
      library(ggplot2)
if("RColorBrewer" %in% installed.packages("RColorBrewer") == FALSE)install.packages("RColorBrewer")
      library(RColorBrewer)
if("reshape" %in% installed.packages("reshape") == FALSE)install.packages("reshape")
      library(reshape)
```

## font
```{r}
if("extrafont" %in% installed.packages("extrafont") == FALSE)install.packages("extrafont")
      library(extrafont)
```

## ga
```{r}
if("RGA" %in% installed.packages("RGA") == FALSE)install.packages("RGA")
      library(RGA)
if("ggmap" %in% installed.packages("ggmap") == FALSE)install.packages("ggmap")
      library(ggmap)
if("googleVis" %in% installed.packages("googleVis") == FALSE)install.packages("googleVis")
      library(googleVis)
```
